---
title: Climate correlates of covid19 incidence in the provinces in Spain: A spatial SUR analysis
author:
  - name: Author A
    email: authora@institution.edu
    affiliation: University
    footnote: 1
  - name: Autor B
    email: bob@example.com
    affiliation: School
address:
  - code: University
    address: Department, Street, City, State, Zip
  - code: School
    address: Department, Street, City, State, Zip
footnote:
  - code: 1
    text: "Corresponding Author"
  - code: 2
    text: "Equal contribution"
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "Geographical Analysis"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
#linenumbers: true
#numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
---

Introduction
==========================

The literature about COVID-19 suggested that population density is the one of the most important proliferate cause of these viscous, however this ill spread with different intensity at big cities of the world. Controlling for socioeconomic characteristics the objective of this paper is observe the effect of clime on COVID-19  proliferation.

To answer this question, we are working with Spain data set. Spain is one of the countries infected by the COVID-19, when analyzed is possible to discover  how the virus behaves and proliferate in differenthumidity and temperatures caused by the diverse climate. The country is divided in 50 provinces. 

The influence of environmental factors on respiratory viral diseases has been investigated for a long time. Diverse studies have shown the effect of temperature and humidity on transmission rates of influenza and the various types of severe acute respiratory syndrome coronavirus (SARS-CoV). A few years ago, some studies had already begun to demonstrate the close relation between cold exposure and acute respiratory tract infections caused by viruses (Mäkinen et al. 2009; Casanova et al. 2010; Sun et al. 2020; Liener et al. 2003; Kudo et al. 2019).

Jaakkola et al. revealed that a decrease of temperature and absolute humidity precedes the onset of symptoms of influenza A and B virus by 3 days in places where the temperature is low (Jaakkola et al. 2014). Chan et al. had already demonstrated that virus viability was lost when temperatures are above 38 °C and relative humidity is above 95%, suggesting that the better stability and transmission of SARS-CoV is at low temperature and low humidity environment (Chan et al. 2011).  These parameters could better explain the fast transmission of SARS-CoV in subtropical areas, such as Hong Kong, in comparison to some countries in tropical areas, such as Malaysia and Thailand, with higher temperatures and high relative humidity environment.

	Another condition that is related to respiratory infections is vitamin D deficiency, which could be find in some natural foods, such as oily fish like eel, salmon and cod liver oil. Meanwhile, to supply the needs of vitamin D in the body, it is not enough ingest the adequate dietary intake of it, but it is essential to be exposed to solar ultraviolet radiation (UVB radiation specifically) in order that the vitamin be converted to its active form, 1,25-Dihydroxicalciferol. Instead of that, vitamin D deficiency affects more than 1 billion of people worldwide specially children and elderly people worldwide (Dąbrowska-Leonik et al. 2018) and it has been estimated that approximately 60% of adults are vitamin D deficient in the world (Daly et al. 2012).
	
	Vitamin D deficiency or insufficiency is defined as a 25-hydroxyvitamin D level, in other words, after vitamin D precursor be activated by UVB radiation (Van Schoor and Lips 2011; Wacker and Holick 2013). The main causes for worldwide deficiency in vitamin D is inadequate sun exposure, because of extensive clothing cover, modern habits of indoor environment and, so, air pollution, beyond low ambient UV radiation level, such as high latitude location and duration of autumn and winter seasons (Wacker and Holick 2013; Holick 2017). Indeed, subtropical countries present the highest incidence of general population deficient in 25-hydroxivitamin D: Russian Federation, China, India, North Africa, Canada, Middle East, Europe (Holick 2017; Van Schoor and Lips 2011; Palacios and Gonzalez 2014), while countries localized near Equator line present the smallest incidence of population deficient.
	
	It’s important highlights that vitamin D has known immune-modulatory properties, as enhances innate immune response and promotes the production of cathelicidin, an antimicrobial peptide that has direct antiviral effects against influenza (White et al. 2017; Barlow et al. 2011). Thus, vitamin D deficiency is a condition that facilitates infectious conditions (Prietl et al. 2013; Chang and Lee 2019; Azrielant and Shoenfeld 2017). Nowadays, with the modern lifestyle habits worldwide, the number of people who expose themselves daily to the sun is quite small, in addition to the influence of eating habits (Zakharova et al. 2019; Chang and Lee 2019; Hussain Gilani et al. 2019). 
	
The prevalence and severity of acute respiratory tract has been related to the less exposure to UVB radiation, specially who live furthest from the Equator line, the seasonality of these viral infections and vitamin D deficiency (Zittermann et al. 2016; Dąbrowska-Leonik et al. 2018; Dinlen et al. 2016; Mathyssen et al. 2017; Esposito and Lelii 2015; Jat 2017; Moriyama, Hugentobler, and Iwasaki 2020). Some of the findings are that these patients also presented IgG deficiency (Dąbrowska-Leonik et al. 2018) and dysfunctional macrophage activity (Dinlen et al. 2016).

References

Azrielant, Shir, and Yehuda Shoenfeld. 2017. “Vitamin D and the Immune System.” The Israel Medical Association Journal 19: 7–8.
Barlow, Peter G., Pavel Svoboda, Annie Mackellar, Anthony A. Nash, Ian A. York, Jan Pohl, Donald J. Davidson, and Ruben O. Donis. 2011. “Antiviral Activity and Increased Host Defense against Influenza Infection Elicited by the Human Cathelicidin LL-37.” PLoS ONE 6 (10). https://doi.org/10.1371/journal.pone.0025333.
Casanova, Lisa M., Soyoung Jeon, William A. Rutala, David J. Weber, and Mark D. Sobsey. 2010. “Effects of Air Temperature and Relative Humidity on Coronavirus Survival on Surfaces.” Applied and Environmental Microbiology 76 (9): 2712–17. https://doi.org/10.1128/AEM.02291-09.
Chan, K. H., J. S.Malik Peiris, S. Y. Lam, L. L.M. Poon, K. Y. Yuen, and W. H. Seto. 2011. “The Effects of Temperature and Relative Humidity on the Viability of the SARS Coronavirus.” Advances in Virology 2011. https://doi.org/10.1155/2011/734690.
Chang, Szu Wen, and Hung Chang Lee. 2019. “Vitamin D and Health - The Missing Vitamin in Humans.” Pediatrics and Neonatology 60 (3): 237–44. https://doi.org/10.1016/j.pedneo.2019.04.007.
Dąbrowska-Leonik, Nel, Ewa Bernatowska, Małgorzata Pac, Wiktor Filipiuk, Jan Mulawka, Barbara Pietrucha, Edyta Heropolitańska-Pliszka, Katarzyna Bernat-Sitarz, Beata Wolska-Kuśnierz, and Bożena Mikołuć. 2018. “Vitamin D Deficiency in Children with Recurrent Respiratory Infections, with or without Immunoglobulin Deficiency.” Advances in Medical Sciences 63 (1): 173–78. https://doi.org/10.1016/j.advms.2017.08.001.
Daly, Robin M., Claudia Gagnon, Zhong X. Lu, Dianna J. Magliano, David W. Dunstan, Ken A. Sikaris, Paul Z. Zimmet, Peter R. Ebeling, and Jonathan E. Shaw. 2012. “Prevalence of Vitamin D Deficiency and Its Determinants in Australian Adults Aged 25 Years and Older: A National, Population-Based Study.” Clinical Endocrinology 77 (1): 26–35. https://doi.org/10.1111/j.1365-2265.2011.04320.x.
Dinlen, Nurdan, Aysegul Zenciroglu, Serdar Beken, Arzu Dursun, Dilek Dilli, and Nurullah Okumus. 2016. “Association of Vitamin D Deficiency with Acute Lower Respiratory Tract Infections in Newborns.” Journal of Maternal-Fetal and Neonatal Medicine 29 (6): 928–32. https://doi.org/10.3109/14767058.2015.1023710.
Esposito, Susanna, and Mara Lelii. 2015. “Vitamin D and Respiratory Tract Infections in Childhood.” BMC Infectious Diseases 15 (1): 1–10. https://doi.org/10.1186/s12879-015-1196-1.
Holick, Michael F. 2017. “The Vitamin D Deficiency Pandemic: Approaches for Diagnosis, Treatment and Prevention.” Reviews in Endocrine and Metabolic Disorders 18 (2): 153–65. https://doi.org/10.1007/s11154-017-9424-1.
Hussain Gilani, Syed Yasir, Saima Bibi, Afsheen Siddiqui, Syed Raza Ali Shah, Faiza Akram, and Mujeeb Ur Rehman. 2019. “Obesity And Diabetes As Determinants Of Vitamin D Deficiency.” Journal of Ayub Medical College, Abbottabad : JAMC 31 (3): 432–35.
Jaakkola, Kari, Annika Saukkoriipi, Jari Jokelainen, Raija Juvonen, Jaana Kauppila, Olli Vainio, Thedi Ziegler, Esa Rönkkö, Jouni J.K. Jaakkola, and Tiina M. Ikäheimo. 2014. “Decline in Temperature and Humidity Increases the Occurrence of Influenza in Cold Climate.” Environmental Health: A Global Access Science Source 13 (1): 1–8. https://doi.org/10.1186/1476-069X-13-22.
Jat, Kana Ram. 2017. “Vitamin D Deficiency and Lower Respiratory Tract Infections in Children: A Systematic Review and Meta-Analysis of Observational Studies.” Tropical Doctor 47 (1): 77–84. https://doi.org/10.1177/0049475516644141.
Kudo, Eriko, Eric Song, Laura J. Yockey, Tasfia Rakib, Patrick W. Wong, Robert J. Homer, and Akiko Iwasaki. 2019. “Low Ambient Humidity Impairs Barrier Function and Innate Resistance against Influenza Infection.” Proceedings of the National Academy of Sciences of the United States of America 166 (22): 10905–10. https://doi.org/10.1073/pnas.1902840116.
Liener, Kristina, Richard Leiacker, Jörg Lindemann, Gerhard Rettinger, and Tilman Keck. 2003. “Nasal Mucosal Temperature after Exposure to Cold, Dry Air and Hot, Humid Air.” Acta Oto-Laryngologica 123 (7): 851–56. https://doi.org/10.1080/00016480310000601a.
Mäkinen, Tiina M., Raija Juvonen, Jari Jokelainen, Terttu H. Harju, Ari Peitso, Aini Bloigu, Sylvi Silvennoinen-Kassinen, Maija Leinonen, and Juhani Hassi. 2009. “Cold Temperature and Low Humidity Are Associated with Increased Occurrence of Respiratory Tract Infections.” Respiratory Medicine 103 (3): 456–62. https://doi.org/10.1016/j.rmed.2008.09.011.
Mathyssen, Carolien, Ghislaine Gayan-Ramirez, Roger Bouillon, and Wim Janssens. 2017. “Vitamin D Supplementation in Respiratory Diseases: Evidence from Randomized Controlled Trials.” Polish Archives of Internal Medicine 127 (11): 775–84. https://doi.org/10.20452/pamw.4134.
Moriyama, Miyu, Walter J Hugentobler, and Akiko Iwasaki. 2020. “Seasonality of Respiratory Viral Infections.” Annual Review of Virology, 1–19. https://doi.org/10.1146/annurev-virology-012420-022445.
Palacios, Cristina, and Lilliana Gonzalez. 2014. “Is Vitamin D Deficiency a Major Global Public Health Problem?” Journal of Steroid Biochemistry and Molecular Biology October (144PA): 138–45. https://doi.org/10.1016/j.jsbmb.2013.11.003.
Prietl, Barbara, Gerlies Treiber, Thomas R. Pieber, and Karin Amrein. 2013. “Vitamin D and Immune Function.” Nutrients 5 (7): 2502–21. https://doi.org/10.3390/nu5072502.
Schoor, Natasja M. Van, and Paul Lips. 2011. “Worldwide Vitamin D Status.” Best Practice and Research: Clinical Endocrinology and Metabolism 25 (4): 671–80. https://doi.org/10.1016/j.beem.2011.06.007.
Sun, Zhong, Karuppiah Thilakavathy, S. Suresh Kumar, Guozhong He, and Shi V. Liu. 2020. “Potential Factors Influencing Repeated SARS Outbreaks in China.” International Journal of Environmental Research and Public Health 17 (5): 1–11. https://doi.org/10.3390/ijerph17051633.
Wacker, Matthias, and Michael F Holick. 2013. “Sunlight and Vitamin D: A Global Perspective for Health.” Dermato-Endocrinology 5 (March): 51–108. https://doi.org/10.4161/derm.24476.
White, Mitchell R., Shweta Tripathi, Anamika Verma, Paul Kingma, Kazue Takahashi, Jens Jensenius, Steffen Thiel, Guangshun Wang, Erika C. Crouch, and Kevan L. Hartshorn. 2017. “Collectins, H-Ficolin and LL-37 Reduce Influence Viral Replication in Human Monocytes and Modulate Virus-Induced Cytokine Production.” Innate Immunity 23 (1): 77–88. https://doi.org/10.1177/1753425916678470.
Zakharova, Irina, Leonid Klimov, Victoria Kuryaninova, Irina Nikitina, Svetlana Malyavskaya, Svetlana Dolbnya, Anna Kasyanova, et al. 2019. “Vitamin D Insufficiency in Overweight and Obese Children and Adolescents.” Frontiers in Endocrinology 10 (MAR). https://doi.org/10.3389/fendo.2019.00103.
Zittermann, Armin, Stefan Pilz, Harald Hoffmann, and Winfried März. 2016. “Vitamin D and Airway Infections: A European Perspective.” European Journal of Medical Research 21 (1): 1–10. https://doi.org/10.1186/s40001-016-0208-y.

Context and Data
============

## Covid-19 in Spain

Background information go here.

## Sources of data and data preparation

Explain the sources of data and data preprocessing.


Methods: Spatial SUR
===================

Do not forget to plug-in a reference to the package for spatial sur.


Analysis and Results
===================

Here are two sample references: @Feynman1963118 [@Dirac1953888].


Discussion
===================

Possibly do some simulations with the model.


Concluding Remarks
===================

More words go here.


References {#references .unnumbered}
==========
